const fs=require('fs'), src=fs.readFileSync('local-ide.src.html','utf8');
const a=src.indexOf('    // Source-resident Tool Descriptor'), b=src.indexOf('    // Sync Library Indicators',a);
const store={}; global.localStorage={getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k]};
const vault={'lib-pdfjs':{textContent:'main'},'lib-pdfjs-worker':{textContent:'worker'}};
const api=new Function('document',src.slice(a,b)+';return {parseToolDescriptor,validateToolIntegration,compileAppSource,injectStickShiftCompliance,unpackInlinedLibraries,toolSkillBlocks};')({getElementById:id=>vault[id]||null});
let fail=0; const ok=(n,v)=>{console.log((v?'PASS ':'FAIL ')+n);if(!v)fail++};
const descriptor=`<!-- HTML_IDE_REGION:tool-descriptor:start --><script id="tool-descriptor" type="application/json">{"schema":"stickshift-tool","version":"1.0","file":"{{TOOL_FILE}}","title":"{{TOOL_TITLE}}","description":"demo","open":{"protocol":"HTML_OPEN","tool":"{{TOOL_FILE}}"},"skill":null}</script><!-- HTML_IDE_REGION:tool-descriptor:end -->`;
const plain='<html><body>plain</body></html>'; ok('standalone compiles',api.compileAppSource(plain,{fileName:'plain.html'}).html.includes('plain'));
ok('descriptor without skill validates',api.validateToolIntegration('<html><body>'+descriptor+'</body></html>',false).ok);
const noSkill=api.compileAppSource('<html><body>'+descriptor+'</body></html>',{fileName:'pomodoro-clock.html',embedStickShift:true}).html; ok('setup no skill has open block only',noSkill.includes('tool: pomodoro-clock.html')&&!noSkill.includes('ss-copy-skill'));
const withSkill=descriptor.replace('"skill":null','"skill":{"elementId":"tool-skill","slug":"{{SKILL_SLUG}}"}')+'<!-- HTML_IDE_REGION:tool-skill:start --><script id="tool-skill" type="text/markdown">---\nname: {{SKILL_SLUG}}\n---\nUse {{TOOL_TITLE}}.</script><!-- HTML_IDE_REGION:tool-skill:end -->';
const compiled=api.compileAppSource('<html><body>'+withSkill+'</body></html>',{fileName:'demo.html',embedStickShift:true}).html; ok('skill setup copies authored skill',compiled.includes('Copy Tool Skill')&&compiled.includes('name: demo')); ok('placeholders resolved only compiled',!compiled.includes('{{SKILL_SLUG}}')); ok('no fallback skill injected',!compiled.includes('id="stickshift-skill"'));
ok('contradictory descriptor fails',!api.validateToolIntegration('<html><body>'+descriptor+withSkill.match(/<!-- HTML_IDE_REGION:tool-skill[\s\S]*/)[0]+'</body></html>',false).ok);
const legacy='<html><body><!-- STICKSHIFT_SKILL_START --><script id="stickshift-skill" type="text/markdown">specific instructions</script><!-- STICKSHIFT_SKILL_END --></body></html>'; ok('legacy authored skill hoisted',api.unpackInlinedLibraries(legacy).includes('id="tool-skill"'));
ok('IDE coding skill named once', (src.match(/id="ide-coding-skill"/g)||[]).length===1 && !src.includes('ss-skill-template-input'));
if(fail)process.exit(1);
